name: Publish dataset release

env:
  GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
  GOOGLE_CLOUD_CREDENTIALS: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  publish_data_release:
    name: Publish dataset release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.x"
          architecture: "x64"

      - name: Install sotaque-brasileiro
        run: |
          pip install -e .

      - name: Setup ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        id: setup-ffmpeg

      - name: Setup libsndfile
        run: |
          sudo apt-get install libsndfile1-dev

      - name: Build dataset release
        run: |
          python3 scripts/gh-actions-release-data.py

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Upload dataset release with daily tag
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.date.outputs.date }}
          prerelease: false
          title: "Sotaque Brasileiro"
          files: |
            sotaque-brasileiro-*.zip
